# Generated by Django 2.2.1 on 2019-09-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(editable=False, max_length=255)),
                ('created_on', models.CharField(editable=False, max_length=255)),
                ('purchase_date', models.DateTimeField(blank=True)),
                ('item', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'expense',
            },
        ),
    ]
